COMPOUND_EXTENSIONS = [
    ".tar.gz.bak",
    ".tar.gz",
    ".tar.bz2",
    ".tar.xz",
    ".tar.zst",
    ".tar.lz",
    ".tar.lzma",
    ".tar.Z",
    ".tar.bak",
    ".user.js",
    ".meta.js",
    ".d.ts",
    ".spec.js",
    ".test.js",
    ".spec.ts",
    ".test.ts",
    ".min.js",
    ".min.css",
    ".config.js",
    ".config.ts",
    ".config.json",
    ".config.yaml",
    ".config.yml",
    ".log.gz",
    ".bak.gz",
]

COMPOUND_EXTENSIONS.sort(key=len, reverse=True)